# docker-compose のバージョン
version: '3'

# 各コンテナの情報
services:
  # postgres サービス
  postgres:
    ports:
      - "5432:5432"
    # コンテナの名前
    container_name: postgres
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    # postgres 設定
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db

  # golang アプリケーション
  app:
    container_name: deer
    # postgres をビルドした後に app をビルド
    depends_on:
      - postgres
    # Dockerfile を指定
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    # GOPATHを指定
    environment:
      - GOPATH=/go
    ports:
      - "8080:8080"
    # command: realize
    tty:
      true
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/deer/
    working_dir: /go/src/deer/go/src
    # docker-compose run 実行時に実行されるコマンド
    command: bash -c "realize start"
    #command: bash -c "reflex -r '(\.go$|go\.mod)' -s go run && go run"
    # command: bash -c "air"