settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: chat
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    - html
    - js
    - css
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
